### ISSUE TITLE
Running on Windows yields errors

### ISSUE THREAD

**Issue by ctartamella** [mmcc007/fledge#16]
Attempting to set up a new project running on Windows.  It appears there are some path checks that may be incorrect on Windows.  I get the following stack:

```
Bad state: Not running from source in the Dart repo.
package:fledge/src/io.dart 552:5                                                  dartRepoRoot.<fn>
package:fledge/src/io.dart 566:3                                                  dartRepoRoot
package:fledge/src/io.dart 550:14                                                 dartRepoRoot
package:fledge/src/io.dart 904:20                                                 _pathTo7zip.<fn>
package:fledge/src/io.dart 905:3                                                  _pathTo7zip
package:fledge/src/io.dart 902:14                                                 _pathTo7zip
package:fledge/src/io.dart 924:40                                                 _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:fledge/src/io.dart 820:20                                                 withTempDir
===== asynchronous gap ===========================
package:fledge/src/io.dart 915:10                                                 _extractTarGzWindows
package:fledge/src/io.dart 842:18                                                 extractTarGz
===== asynchronous gap ===========================
package:fledge/src/commands/config.dart 84:9                                      unpackTarGzFile
===== asynchronous gap ===========================
package:fledge/src/commands/config.dart 48:15                                     ConfigCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 196:27                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:fledge/src/command_runner.dart 158:39                                     FledgeCommandRunner.runCommand.<fn>
dart:async                                                                        new Future.sync
package:fledge/src/utils.dart 109:12                                              captureErrors.<fn>
dart:async                                                                        runZoned
package:fledge/src/utils.dart 126:5                                               captureErrors
package:fledge/src/command_runner.dart 158:13                                     FledgeCommandRunner.runCommand
===== asynchronous gap ===========================
package:fledge/src/command_runner.dart 107:11                                     FledgeCommandRunner.run
===== asynchronous gap ===========================
..\..\flutter\.pub-cache\hosted\pub.dartlang.org\fledge-0.1.3\bin\main.dart 4:25  main
This is an unexpected error. Please run

    fledge --trace config -b gitlab

and include the logs in an issue on https://github.com/mmcc007/fledge/issues/new
```

**Comment by mmcc007** [comment]
From the source code, it looks like it is searching for 7zip executable, like 7za.exe. 

You can download it from:
https://www.7-zip.org/

If it is in your path, it should be able to find it.

Hope this helps!

**Comment by jassimjinnah** [comment]
Running "flutter pub get" in fluty...
Bad state: Could not find 7zip.
package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip
package:pub/src/io.dart                   _pathTo7zip
package:pub/src/io.dart 827:22            extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 773:12            withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25            extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12    Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
