### ISSUE TITLE
Bad state: Not running from source in the Dart repo.

### ISSUE THREAD

**Issue by JordyBaylac** [mmcc007/fledge#24]
I got this error after running fledge config -b gitlab --trace on Windows
I already followed comments on [Issue 16](https://github.com/mmcc007/fledge/issues/16) and nothing.
```
C:\Users\jbaylac\Documents\projects\consumer_mobile>fledge config -b gitlab --trace
Bad state: Not running from source in the Dart repo.
package:fledge/src/io.dart 552:5   dartRepoRoot.<fn>
package:fledge/src/io.dart 566:3   dartRepoRoot
package:fledge/src/io.dart 550:14  dartRepoRoot
package:fledge/src/io.dart 904:20  _pathTo7zip.<fn>
package:fledge/src/io.dart 905:3   _pathTo7zip
package:fledge/src/io.dart 902:14  _pathTo7zip
package:fledge/src/io.dart 924:40  _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
dart:async                         _AsyncAwaitCompleter.completeError
package:fledge/src/io.dart         _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
dart:async                         _asyncThenWrapperHelper
package:fledge/src/io.dart         _extractTarGzWindows.<fn>
package:fledge/src/io.dart 820:20  withTempDir
---- Log transcript ----
IO  : Spawning "cmd /c ver" in C:\Users\jbaylac\Documents\projects\consumer_mobile\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.17134.706]
    | Nothing output on stderr.
IO  : unpacking package:fledge/resource/fastlane/fastlane.tar.gz to .
FINE: Extracting .tar.gz stream to ..
IO  : Created temp directory C:\Users\jbaylac\AppData\Local\Temp\pub_671e8dba-7016-11e9-940b-04d3b0c275ad
IO  : Creating C:\Users\jbaylac\AppData\Local\Temp\pub_671e8dba-7016-11e9-940b-04d3b0c275ad\data.tar.gz from stream.
FINE: Created C:\Users\jbaylac\AppData\Local\Temp\pub_671e8dba-7016-11e9-940b-04d3b0c275ad\data.tar.gz from stream.
IO  : Deleting directory C:\Users\jbaylac\AppData\Local\Temp\pub_671e8dba-7016-11e9-940b-04d3b0c275ad.
ERR : Bad state: Not running from source in the Dart repo.
FINE: Exception type: StateError
ERR : package:fledge/src/io.dart 552:5   dartRepoRoot.<fn>
    | package:fledge/src/io.dart 566:3   dartRepoRoot
    | package:fledge/src/io.dart 550:14  dartRepoRoot
    | package:fledge/src/io.dart 904:20  _pathTo7zip.<fn>
    | package:fledge/src/io.dart 905:3   _pathTo7zip
    | package:fledge/src/io.dart 902:14  _pathTo7zip
    | package:fledge/src/io.dart 924:40  _extractTarGzWindows.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                         _AsyncAwaitCompleter.completeError
    | package:fledge/src/io.dart         _extractTarGzWindows.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                         _asyncThenWrapperHelper
    | package:fledge/src/io.dart         _extractTarGzWindows.<fn>
    | package:fledge/src/io.dart 820:20  withTempDir
---- End log transcript ----
```

**Comment by mmcc007** [comment]
I will setup a windows environment and see if I can reproduce this and get back to you

**Comment by jassimjinnah** [comment]
> I will setup a windows environment and see if I can reproduce this and get back to you

Running "flutter pub get" in fluty...
Bad state: Could not find 7zip.
package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip
package:pub/src/io.dart                   _pathTo7zip
package:pub/src/io.dart 827:22            extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 773:12            withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25            extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12    Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by jassimjinnah** [comment]
> I will setup a windows environment and see if I can reproduce this and get back to you

please help me with this issue
