### ISSUE TITLE
Why not using fastlane directly ?

### ISSUE THREAD

**Issue by bitsydarel** [mmcc007/fledge#25]
Hi, great lib.

I have few questions if you don’t mind.

As far as I understand, fledge’s just wrapping fastlane functionality. Which mean that fledge is dependent on ruby, bundle being installed.

So my first question is why not just directly use fastlane over fledge? 

What are the advantages that fledge offers besides creating the platform specific fastlane folders?

Second the tool’s expecting a specific git branch name (dev), what if we have different setup for our branch naming?

**Comment by mmcc007** [comment]
fledge is intended to provide CI/CD support for building, testing and releasing flutter apps for new flutter developers. As you mention, it is currently a thin wrapper around a fastlane implementation. This wrapper is useful for providing a simple interface for unbundling the fastlane files and managing a default development/beta/release pipeline. For new developers, this is intended as a simple way to get started with the often tricky process of releasing flutter apps. 

I plan on adding more command line options and/or a config file to replace hard-coded assumptions and to allow for a more flexible pipeline. More experienced developers can go directly to the fastlane files and customize them for their own needs.
