### ISSUE TITLE
Setting-up 2-step verification in Apple store console

### ISSUE THREAD

**Issue by mmcc007** [mmcc007/fledge#3]
It works. Awesome!

I got a few quirks down the road though. 

First is that my account has  2 step verification enabled. You do mention this in your manual. I created a second account, but when I tried to verify that i could login with it, it asked me to add security questions. I thought this might be another kind of 2 step verification, so I spent half an hour trying to disable it. Turns out it wasn't a problem at all, but maybe you could mention that part in your manual to save overly cautious people like me from this :-)

_Taken from original post by @yvanvds in https://github.com/mmcc007/fledge/issues/2#issuecomment-471615971_

**Comment by mmcc007** [comment]
There is a hint in the manual that advises to log out and log back in again. But I suppose it could be more explicit.

I did not document all the steps at the time and cannot reproduce them easily

Can you suggest some text to add to the docs?

**Comment by yvanvds** [comment]
how about this:

> When creating a new account, you will need to supply another email address. An invitation is sent to that address, which you must use to create a new account. During account creation, you will have to provide a password and three security questions. Two security questions must be answered every time you log in on the apple website because you don't have 2 step verification enabled. Don't worry though: these questions are not triggered when you use the account in a scripted environment like Fledge.
> 
> Warning: NEVER enable 2 step verification for this account. Once you turn it on, it cannot be turned off again.

It know I tend to be a bit verbose. Feel free to shorten this.

**Comment by mmcc007** [comment]
Closed by #15
