### ISSUE TITLE
Team ID required in ios Appfile

### ISSUE THREAD

**Issue by mmcc007** [mmcc007/fledge#4]
Next I also needed to provide my Team ID in the ios Appfile. Perhaps this is only required because i have multiple teams? But again, it could be added to the manual.

_Originally posted by @yvanvds in https://github.com/mmcc007/fledge/issues/2#issuecomment-471615971_

**Comment by mmcc007** [comment]
Do you have an error message or anything that indicates this (so it can be reproduced and documented correctly)?

**Comment by yvanvds** [comment]
Ok. I filled in a fake Team ID and get this result. 
The first error reads:
```
[13:25:59]: Could not set team ID to '118607454', only found the following available teams
- 46266300 (Team1 Name)
- 2015341 (Team2 Name)
```
Fairly sure this is what I got the previous time. After all, when fledge is installed in my project, this is in the Appfile:

```
itc_team_id("118607454") # App Store Connect Team ID
team_id("ET2VMHJPVM") # Developer Portal Team ID
```
I guess these are fake, or from your account? Then follows the Fastlane summary, with the last failed step: upload_to_testflight. At the last line, the previous error is repeated.

**Comment by mmcc007** [comment]
See comment in #13

**Comment by mmcc007** [comment]
Please close if you think this issue is resolved

**Comment by yvanvds** [comment]
I don't think I can close this issue since you've created it.
